#import "imports.typ": *

= Introduction
The Ising Model was introduced by Wilhelm Lenz in 1920 in an effort to describe ferromagnetism. It was then given as a problem to his PhD student, Ernest Ising, from where the name comes. In his 1924 PhD thesis @ising1924, Ising solved the model in 1D using transfer matrices, and arrived a disheartening conclusion, the model does not show a phase transition at non-zero temperature in 1D. He then concluded incorrectly that the model does not show a phase transition at non-zero temperature in any dimension, much to the chagrin of a lot of people interested in explaining ferromagnetism at the time. Ironically, he stopped his research in physics thinking that his proof outlined that the Ising model cannot explain ferromagnets and was physically invalid. He took up teaching which he did for the rest of his life. 12 years later, this argument was disproved by Rudolf Peierls @Peierls1936, who showed that the model does indeed show a phase transition at non-zero temperature in 2D and higher dimensions, using a shoreline proof. In 1944, a breakthrough arrived at the hands of Lars Onsager @Onsager1944, who solved the 2D Ising Model exactly for a zero field Hamiltonian. An excellent review of the history of the Ising Model can be found at @BRUSH1967 @Taroni2015.

In this report we aim to outline the exact results that have been obtained in the pursuit for the solution of the Ising Model. Most of the report will follow from
the book "Exactly Solved Models in Statistical Physics" by R.J. Baxter @baxter1982. Another Reference that I used while studying this is "A Students Guide to the Ising Model" by James S. Walker @walker2023. First we outline the solution to the 1D ising Model using Ising solution of transfer matrices and conclude why the 1D model does not show a phase transition at non-zero temperature, using spin correlations. Then we outline the solution of the mean field model and how that shows phase transitions at non-zero temperature.

Finally, we solve the 2D Ising model as done in @baxter1982, by constructing corner transfer matrices. For the ease of reading, after each section there is a summary of the results obtained in that section in a blue box.

